### ISSUE TITLE
在CQU-openlib内引用的请求

### ISSUE THREAD

**Issue by INFO-studio** [haowang-cqu/CQU-Logo#2]
我们正在维护一个项目[CQU-openlib](https://cqu-openlib.cn)，希望能够在站内引用您项目内的资料，故作此请求。
当然，我们十分尊重著作人的贡献，您可以自行选择以下的所有内容。

- 可以引用/不可以引用
- 可以放入本站资源集合以供直链下载便利/只能提供指向此项目的github链接
- 自定义署名（请说明）/完全匿名
- 自行/由我们代办 删除/保留 文件内的个人信息

作为重庆大学学子，我们十分感激您做出的所有贡献，无论是否同意本请求。
如您同意，您也可以额外提供一个个人介绍的md文件，我们会放在[贡献者](https://cqu-openlib.cn/%E8%B4%A1%E7%8C%AE%E8%80%85/)一栏，同时在您提供的资料处超链接至此文件。
再次表达对您的感谢！

**Comment by haowang02** [comment]
感谢您对本仓库的关注。CQU-openlib是一个很棒的项目，我很乐意您在其中引用本仓库的任何内容，只需要在适当标注来源即可。最后感谢您对CQU-openlib的积极维护，这对重大学子意义非凡！

**Comment by INFO-studio** [comment]
感谢您的支持，需要署名嘛

**Comment by haowang02** [comment]
不必署名，引用本仓库的链接即可

**Comment by INFO-studio** [comment]
感谢您的支持，该项目收录于：
[重庆大学视觉形象 - 重庆大学资源共享计划](https://cqu-openlib.cn/academic/%E9%87%8D%E5%BA%86%E5%A4%A7%E5%AD%A6%E8%A7%86%E8%A7%89%E5%BD%A2%E8%B1%A1/)
与此同时，有一些小问题，详见[#3](https://github.com/haowang-cqu/CQU-Logo/issues/3)
