### ISSUE TITLE
【bug】校徽+中文校名（竖排）的蓝色与黑色不能重合

### ISSUE THREAD

**Issue by INFO-studio** [haowang-cqu/CQU-Logo#3]
如下图
黑色校名较为居中，而蓝色校名较为偏右
![image](https://github.com/user-attachments/assets/003e25a5-93a7-4cfb-b21a-2392464bb475)

**Comment by INFO-studio** [comment]
#4

**Comment by haowang02** [comment]
感谢修正，非常细节！PR已合并。
